encoding: utf-8
name: Gi-Cheon Kang
url: http://gicheonkang.com
author:
  name: Gi-Cheon Kang
  email: gchnkang@gmail.com
description: AI PhD student at Seoul National University.
permalink: /posts/:title/
include: ['_pages']
