encoding: utf-8
name: Junghyun Kim
url: https://jhkim-snu.github.io
author:
  name: Junghyun Kim
  email: jkim.aiforall@gmail.com
description: Ph.D. in Artificial Intelligence, SNU. Postdoctoral Research Fellow at AIIS, SNU. Research Fellow at OpenMind, San Francisco Bay Area.
permalink: /posts/:title/
include: ['_pages']
